# 定义应用程序名称
spring:
  application:
    name: flyapi-backend

# 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyapi
    username: root
    password: 123456

  # Spring MVC 配置
  mvc:
    # 使用 ANT 风格的路径匹配策略
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # session 失效时间（分钟）
  session:
    timeout: 86400

# 应用服务器配置
server:
  port: 7529
  # 定义应用程序的上下文路径
  servlet:
    context-path: /api

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    # 配置下划线转驼峰命名法
    map-underscore-to-camel-case: false
    # 打印 SQL 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置逻辑删除的字段名
      logic-delete-field: isDelete
      # 配置逻辑已删除的值
      logic-delete-value: 1
      # 配置逻辑未删除的值
      logic-not-delete-value: 0

# 自定义配置
flyapi:
  client:
    # 配置客户端的访问密钥
    access-key: dango
    secret-key: abcdefgh

# Dubbo 配置
dubbo:
  application:
    # 定义应用程序名称
    name: dubbo-springboot-demo-provider
  protocol:
    # 配置 Dubbo 协议
    name: dubbo
    port: -1
  registry:
    # 配置注册中心
    id: nacos-registry
    address: nacos://8.130.31.245:8848
