# 数据库连接配置
spring:
  datasource:
    # 配置 JDBC 驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置数据库连接 URL
    url: jdbc:mysql://localhost:3306/flyapi
    # 配置数据库用户名
    username: root
    # 配置数据库密码
    password: 123456